// <auto-generated />
using System;
using Cifralite.Web.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cifralite.Web.Core.Data.Migrations
{
    [DbContext(typeof(ContextoBD))]
    partial class ContextoBDModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Cifralite.Web.Core.Entities.Musica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artista")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tempo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tom")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Musicas", (string)null);
                });

            modelBuilder.Entity("Cifralite.Web.Core.Entities.Secao", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acordes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdMusica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdMusica");

                    b.ToTable("Secoes", (string)null);
                });

            modelBuilder.Entity("Cifralite.Web.Core.Entities.Secao", b =>
                {
                    b.HasOne("Cifralite.Web.Core.Entities.Musica", "Musica")
                        .WithMany("Secoes")
                        .HasForeignKey("IdMusica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musica");
                });

            modelBuilder.Entity("Cifralite.Web.Core.Entities.Musica", b =>
                {
                    b.Navigation("Secoes");
                });
#pragma warning restore 612, 618
        }
    }
}
